tinderapi:
  baseuri: https://api.gotinder.com

server:
  servlet:
    context-path: /

spring:
  devtools:
    livereload:
      enabled: false

logging:
  level:
    root: WARN
    com.wgcorp: DEBUG

---
spring.profiles: dev

tinderapi:
  baseuri:



