# User infos required in order to get the tinder api access_token
facebook:
  id:
  email:
  password:

tinderapi:
  baseuri: https://api.gotinder.com
  xAuthToken:

server:
  servlet:
    context-path: /

spring:
  devtools:
    livereload:
      enabled: false

---
spring.profiles: dev

tinderapi:
  baseuri:



